-- 20 candidate questions for Reasoning Level 1, Chapter 1: 'Odd One Out'
-- Generated by Claude, land as status='pending' for review in the admin panel's
-- Question Review tab. Correct-answer position deliberately varied across
-- A/B/C/D (not clustered) so the answer position itself gives no pattern away.
-- Run in the Supabase SQL editor after pending_questions_schema.sql.

INSERT INTO pending_questions (vertical, chapter_id, chapter_title, level, question_en, options, correct_index, explanation, status) VALUES
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Carrot, Apple, Banana, Mango?',
  '["Apple", "Banana", "Mango", "Carrot"]'::jsonb,
  3,
  'Apple, Banana, and Mango are all fruits. Carrot is a vegetable — it breaks the shared pattern.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Guitar, Violin, Football, Flute?',
  '["Guitar", "Violin", "Football", "Flute"]'::jsonb,
  2,
  'Guitar, Violin, and Flute are all musical instruments. Football is a sport, not an instrument.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Dog, Cat, Table, Lion?',
  '["Dog", "Cat", "Table", "Lion"]'::jsonb,
  2,
  'Dog, Cat, and Lion are all animals. Table is a piece of furniture, not a living thing.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Happy, Red, Blue, Green?',
  '["Happy", "Red", "Blue", "Green"]'::jsonb,
  0,
  'Red, Blue, and Green are all colours. Happy is a feeling, not a colour.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Circle, Cloud, Square, Triangle?',
  '["Circle", "Square", "Triangle", "Cloud"]'::jsonb,
  3,
  'Circle, Square, and Triangle are all defined geometric shapes. A cloud has no fixed shape.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: January, Monday, Tuesday, Friday?',
  '["January", "Monday", "Tuesday", "Friday"]'::jsonb,
  0,
  'Monday, Tuesday, and Friday are all days of the week. January is a month.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Rose, Mango, Lotus, Sunflower?',
  '["Rose", "Mango", "Lotus", "Sunflower"]'::jsonb,
  1,
  'Rose, Lotus, and Sunflower are all flowers. Mango is a fruit.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Banana, Pen, Pencil, Eraser?',
  '["Banana", "Pen", "Pencil", "Eraser"]'::jsonb,
  0,
  'Pen, Pencil, and Eraser are all stationery items used for writing. Banana is a fruit.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Car, Tree, Bus, Bicycle?',
  '["Car", "Bus", "Bicycle", "Tree"]'::jsonb,
  3,
  'Car, Bus, and Bicycle are all vehicles used for transport. Tree is a plant.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Delhi, Mumbai, India, Chennai?',
  '["Delhi", "Mumbai", "India", "Chennai"]'::jsonb,
  2,
  'Delhi, Mumbai, and Chennai are all cities. India is a country — a different level of classification.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Piano, Cricket, Football, Hockey?',
  '["Piano", "Cricket", "Football", "Hockey"]'::jsonb,
  0,
  'Cricket, Football, and Hockey are all sports. Piano is a musical instrument.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Eagle, Sparrow, Butterfly, Crow?',
  '["Eagle", "Sparrow", "Butterfly", "Crow"]'::jsonb,
  2,
  'Eagle, Sparrow, and Crow are all birds. Butterfly is an insect, not a bird.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Milk, Bread, Curd, Cheese?',
  '["Milk", "Curd", "Cheese", "Bread"]'::jsonb,
  3,
  'Milk, Curd, and Cheese are all dairy products. Bread is made from wheat flour, not milk.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: School, Doctor, Teacher, Engineer?',
  '["School", "Doctor", "Teacher", "Engineer"]'::jsonb,
  0,
  'Doctor, Teacher, and Engineer are all professions (people). School is a place, not a profession.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Triangle, Rectangle, Sphere, Square?',
  '["Triangle", "Rectangle", "Sphere", "Square"]'::jsonb,
  2,
  'Triangle, Rectangle, and Square are all flat, 2D shapes. Sphere is a solid, 3D shape.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Ant, Elephant, Bee, Butterfly?',
  '["Ant", "Elephant", "Bee", "Butterfly"]'::jsonb,
  1,
  'Ant, Bee, and Butterfly are all insects. Elephant is a mammal, much larger and structurally different.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: River, Sun, Moon, Star?',
  '["Sun", "Moon", "Star", "River"]'::jsonb,
  3,
  'Sun, Moon, and Star are all objects seen in the sky. River is a landform on Earth''s surface.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Wheat, Rice, Cotton, Corn?',
  '["Wheat", "Rice", "Cotton", "Corn"]'::jsonb,
  2,
  'Wheat, Rice, and Corn are all food grains people eat. Cotton is a fibre crop, not eaten as food.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Tomato, Orange, Potato, Onion?',
  '["Tomato", "Orange", "Potato", "Onion"]'::jsonb,
  1,
  'Tomato, Potato, and Onion are all vegetables commonly used in cooking. Orange is a fruit.',
  'pending'
),
(
  'Reasoning',
  'odd-one-out',
  'Odd One Out',
  '1',
  'Which one is the odd one out: Piano, Guitar, Painting, Drum?',
  '["Piano", "Guitar", "Painting", "Drum"]'::jsonb,
  2,
  'Piano, Guitar, and Drum are all musical instruments. Painting is a visual art form, not an instrument.',
  'pending'
);