export const CURRICULUM = [
  {
    level: 1,
    name: 'Beginner',
    icon: '🌱',
    lockKey: null,
    lessons: [
      { id: 'l1_01', title: 'Introduction to Vedic Mathematics',                    xp: 50,  isAssessment: false, youtube_video_id: 'Dy4V6yVReRY', videoTeacher: 'Dadi Ji' },
      { id: 'l1_02', title: 'Ekadhikena Purvena — Squaring Numbers Ending in 5',   xp: 60,  isAssessment: false, youtube_video_id: '-bS5q_fLI4o', videoTeacher: 'Dadi Ji' },
      { id: 'l1_03', title: 'Nikhilam — Multiplication Near 10',                    xp: 60,  isAssessment: false, youtube_video_id: 'd_LaXX99e30', videoTeacher: 'Bhavika' },
      { id: 'l1_04', title: 'Nikhilam — Multiplication Near 100',                   xp: 70,  isAssessment: false, youtube_video_id: 'zLbqBL5faWs', videoTeacher: 'Hitansh' },
      { id: 'l1_05', title: 'Nikhilam — Multiplication Near 1000',                  xp: 70,  isAssessment: false, youtube_video_id: 'GBU4YAeXiNE', videoTeacher: 'Bhavika' },
      { id: 'l1_06', title: 'By One More — Digit Sums & Casting Out 9s',            xp: 60,  isAssessment: false, youtube_video_id: 'UMd7TGyWiTc', videoTeacher: 'Dadi Ji' },
      { id: 'l1_07', title: 'Urdhva-Tiryagbhyam — 2-Digit Multiplication',          xp: 80,  isAssessment: false, youtube_video_id: 'XG_XQ0XAVWE', videoTeacher: 'Dadi Ji' },
      { id: 'l1_08', title: 'Multiplication by 11 and 12',                           xp: 70,  isAssessment: false, youtube_video_id: 'TvUzPSLdKe4', videoTeacher: 'Bhavika' },
      { id: 'l1_09', title: 'Multiplication by 9, 99, 999',                          xp: 70,  isAssessment: false, youtube_video_id: '' },
      { id: 'l1_10', title: 'Level 1 Assessment — Beginner Mastery Quiz',            xp: 100, isAssessment: true,  youtube_video_id: '' },
    ],
  },
  {
    level: 2,
    name: 'Intermediate',
    icon: '📈',
    lockKey: 'l1_10',
    lessons: [
      { id: 'l2_01', title: 'Paravartya — Division by Near-Base Numbers',           xp: 80,  isAssessment: false, youtube_video_id: '' },
      { id: 'l2_02', title: 'Urdhva-Tiryagbhyam — 3-Digit Multiplication',          xp: 90,  isAssessment: false, youtube_video_id: '' },
      { id: 'l2_03', title: 'Squaring 2-Digit Numbers — General Method',             xp: 80,  isAssessment: false, youtube_video_id: '' },
      { id: 'l2_04', title: 'Cubing Numbers — Vedic Shortcut',                       xp: 90,  isAssessment: false, youtube_video_id: '' },
      { id: 'l2_05', title: 'Vedic Square Roots — 4-Digit Numbers',                  xp: 90,  isAssessment: false, youtube_video_id: 'nNW6wTYFV9Q', videoTeacher: 'Dadi Ji' },
      { id: 'l2_06', title: 'Vedic Cube Roots — 6-Digit Numbers',                    xp: 90,  isAssessment: false, youtube_video_id: '' },
      { id: 'l2_07', title: 'Digit Sum Verification Method',                          xp: 70,  isAssessment: false, youtube_video_id: '' },
      { id: 'l2_08', title: 'Multiplication by 5, 25, 125',                           xp: 70,  isAssessment: false, youtube_video_id: '' },
      { id: 'l2_09', title: 'Vedic Long Division — 2-Digit Divisors',                xp: 100, isAssessment: false, youtube_video_id: '' },
      { id: 'l2_10', title: 'Fractions — Vedic Addition & Subtraction',              xp: 80,  isAssessment: false, youtube_video_id: '' },
      { id: 'l2_11', title: 'Calendar Calculations — Day of Any Date',               xp: 100, isAssessment: false, youtube_video_id: '' },
      { id: 'l2_12', title: 'Level 2 Assessment — Intermediate Mastery Quiz',        xp: 150, isAssessment: true,  youtube_video_id: '' },
    ],
  },
  {
    level: 3,
    name: 'Advanced',
    icon: '⚡',
    lockKey: 'l2_12',
    lessons: [
      { id: 'l3_01', title: 'Urdhva-Tiryagbhyam — General 2-Digit Method',          xp: 100, isAssessment: false, youtube_video_id: '' },
      { id: 'l3_02', title: 'Nikhilam for Large Numbers',                             xp: 110, isAssessment: false, youtube_video_id: '' },
      { id: 'l3_03', title: 'Anurupyena — Proportional Scaling',                     xp: 110, isAssessment: false, youtube_video_id: '' },
      { id: 'l3_04', title: 'Vinculum — Complement Representation',                  xp: 120, isAssessment: false, youtube_video_id: '' },
      { id: 'l3_05', title: 'Duplex Method — Squaring Any Number',                   xp: 130, isAssessment: false, youtube_video_id: '' },
      { id: 'l3_06', title: 'Cube Roots of Perfect Cubes',                           xp: 140, isAssessment: false, youtube_video_id: '' },
      { id: 'l3_07', title: 'Straight Division',                                      xp: 150, isAssessment: false, youtube_video_id: '' },
      { id: 'l3_08', title: 'Algebraic Multiplication',                               xp: 140, isAssessment: false, youtube_video_id: 'F-6YP7xIzkQ', videoTeacher: 'Bhavika' },
      { id: 'l3_09', title: 'Simultaneous Equations',                                 xp: 150, isAssessment: false, youtube_video_id: '' },
      { id: 'l3_10', title: 'Level 3 Assessment — Advanced Mastery Quiz',            xp: 200, isAssessment: true,  youtube_video_id: '' },
    ],
  },
  {
    level: 4,
    name: 'Master',
    icon: '👑',
    lockKey: 'l3_10',
    lessons: [
      { id: 'l4_01', title: 'Cubing Any Number',                                        xp: 180, isAssessment: false, youtube_video_id: '' },
      { id: 'l4_02', title: 'General Squaring — 3 and 4 Digit Numbers',               xp: 180, isAssessment: false, youtube_video_id: '' },
      { id: 'l4_03', title: 'Osculators — Divisibility Testing',                      xp: 170, isAssessment: false, youtube_video_id: '' },
      { id: 'l4_04', title: 'Auxiliary Fractions',                                    xp: 170, isAssessment: false, youtube_video_id: '' },
      { id: 'l4_05', title: 'Calendar Calculations',                                  xp: 180, isAssessment: false, youtube_video_id: '' },
      { id: 'l4_06', title: 'Square Roots of Imperfect Squares',                      xp: 190, isAssessment: false, youtube_video_id: '' },
      { id: 'l4_07', title: 'Vedic Sutras in Algebra — Factorisation',                xp: 180, isAssessment: false, youtube_video_id: '' },
      { id: 'l4_08', title: 'Master Assessment — Vedic Mathematics Complete',         xp: 300, isAssessment: true,  youtube_video_id: '' },
    ],
  },
];